print('Hello world!')
print("Ram")
print("sahi")
print("safdas.")
#print("yes!f s#sf asdfs ")
print(3 + 2 + 8 + 6 / 89 * 5)
print("what is 3+2?", 3 + 2)
print("Is it greater?", 5 > -2)
print("Is it greater or equal?", 5 >= -2)
print("Is it less or equal?", 5 <= -2)
